apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: zap-api-testtrigger
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    namespace: default
    name: hands-on-testkube
  event: modified
  action: run
  execution: test
  testSelector:
    name: zap-api-test
    namespace: testkube