apiVersion: tests.testkube.io/v3
kind: Test
metadata: 
  name: k6-test-nginx-gitops
  namespace: testkube
  generation: 1
spec:
  content:
    data: |
      import {check, sleep, group} from "k6";
      import http from "k6/http";

      export let options = {
          vus: 10,
          duration: '30s',
          batchPerHost: 4,
          insecureSkipTLSVerify: true,
          thresholds: {
              'http_req_duration{kind:html}': ['avg<=250', 'p(95)<500'],
          }
      };

      export default function () {
          group("static", function () {
              check(http.get(`http://${__ENV.TARGET_HOSTNAME}:80`, {
                  tags: {'kind': 'html'},
              }), {
                  "status is 200": (res) => res.status === 200,
              });
          });
          sleep(1);
      }
    type: string
  executionRequest:
    variables:
      TARGET_HOSTNAME:
        name: TARGET_HOSTNAME
        type: basic
        value: nginx-service.default.svc.cluster.local
        valueFrom: {}
  type: k6/script