apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: hands-on-testkube-gitops
  namespace: testkube
  generation: 1
spec:
  description: Example Testkube test suite via Flux2
  executionRequest: {}
  steps:
  - execute:
      name: k6-test-nginx-gitops
  - delay:
      duration: 1000
  - execute:
      name: gradle-integration-test-gitops
