apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testkube
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: testkube
  targetNamespace: testkube
  chart:
    spec:
      chart: testkube
      sourceRef:
        kind: HelmRepository
        name: testkube
        namespace: flux-system
      version: "1.6.110"
  # values:
  #  testkube-dashboard:
  #    enabled: "true"
  #    ingress:
  #      enabled: "true" 
  #  testkube-api:
  #    ingress:
  #      enabled: "true"

