apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: microservice
  namespace: flux-system
spec:
  interval: 5m0s
  #dependsOn:
  #  - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/overlays/int
  prune: true
