apiVersion: v1
kind: Service
metadata:
  name: zap-webswing
  namespace: zap
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: api
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: zap
    mode: webswing
---
apiVersion: v1
kind: Pod
metadata:
  name: zap-webswing
  namespace: zap
  labels:
    app: zap
    mode: webswing
spec:
  containers:
    - name: zap-webswing
      image: owasp/zap2docker-stable:2.12.0
      args: ['zap-webswing.sh']
      ports:
        - containerPort: 8080
        - containerPort: 8090      
      resources:
        limits:
          cpu: "2"
          memory: "1024Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
