apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hands-on-testkube
  framework: spring

buildMetadata: [managedByLabel]

resources:
  - microservice-deployment.yaml
  - microservice-service.yaml

configMapGenerator:
  - name: application-configmap
    literals:
      - INFO_DEVELOPER=lreimer
      - INFO_GIT_URL=https://github.com/lreimer/hands-on-testkube
