apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

resources:
  # you can also specify a Git repo URL here
  - ../../base/
  - hoverfly-deployment.yaml
  - hoverfly-service.yaml

configMapGenerator:
  - name: application-configmap
    behavior: merge
    literals:
      - INFO_APP_ENV=dev
