kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: maven-test
  labels:
    docs: example
    testkube.io/name: Maven
    testkube.io/group: demo
spec:
  content:
    git:
      uri: https://github.com/lreimer/hands-on-testkube.git
  use:
    - name: official/maven/v1
      config: {}
  container:
    workingDir: /data/repo
  job:
    activeDeadlineSeconds: 60
  steps:
    - name: Saving artifacts
      condition: always
      artifacts:
        paths:
          - target/surefire-reports/**
